<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>数据库字段自动填充 $fields</title>
    <style type="text/css">
    .code {
        font-family: consolas;
        font-size: small;
    }
    .code .kw {
        color: #4880B3;
    }
    .code .field {
        color: #8F702B;
        font-weight: bold;
    }
    .code .str {
        color: #188321;
    }
    .code .var {
        color: #A445C9;
    }
    li {
        padding: 3px 0;
    }
    .tbl-name {
        font-family: arial;
    }
    .f-name {
        font-family: arial;
        font-size: small;
    }
    .tbl-cmt {
        font-size:small;
        color: #6F6F6F;
    }
    .f-cmt {
        font-size:small;
        color: #878A86;
    }
    .high-light {
        background-color: #F3EC3E;
    }
    table.table, table.table td, table.table th {
        border: 1px solid #555964;
        border-collapse: collapse;
    }
    table.table tr:nth-child(2n) {
        background: #F3F6FF;
    }
    table.table th {
        padding: 2px;
        font-weight: bold;
        font-size: small;
        background: #DFF1F8;
    }
    table.table td {
        font-size: small;
        color: #494646;
        padding: 2px;
    }
    table.table td.PRI {
        color: #535151;
        font-weight: bold;
    }
    </style>
</head>
<body>
    <?php include "$tpl.phtml" ?>
</body>